spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userservice}
    username: ${SPRING_DATASOURCE_USERNAME:userservice}
    password: ${SPRING_DATASOURCE_PASSWORD:userservice}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-check-sums: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  cache:
    type: redis

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO